# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c16673e3da10258f4126b49fd79936ac4461294f96c5bdc7d2b21b0d87b31c92a74b910d66bcf3dc7d4cc6d9c2e742b54f519e9fc5d76c8926fcee9ea95c60e

test:
  secret_key_base: 2b3010fbfda58695bc316d7c28c4f9d7abafe722ae7e1e56ace13c25243177adada78f46358fbddde5283299689d261001bb7909be9c9f4fce23c820cda26ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
